### ISSUE TITLE
[BUG] Panic when trying to run the gadget using gadget-cli

### ISSUE THREAD

**Issue by shekohex** [tangle-network/gadget#404]
Trying to run the hello world blueprint's gadget after building result in the following error:

```
thread 'main' panicked at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:135:18:
called `Result::unwrap()` on an `Err` value: InvalidStringLength
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Command Used to run the gadget

```bash
./target/debug/hello-blueprint run --bind-addr 127.0.0.1 --bind-port 6754 --blueprint-id 0 --service-id 0 --chain local_testnet --http-rpc-url http://127.0.0.1:9944 --keystore-uri file://target/keystore --pretty --protocol tangle --ws-rpc-url ws://127.0.0.1:9944
```

Full backtrace:
```rust
thread 'main' panicked at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:135:18:
called `Result::unwrap()` on an `Err` value: InvalidStringLength
stack backtrace:
   0:     0x5651944f69fa - std::backtrace_rs::backtrace::libunwind::trace::had463f8f1f0b6399
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x5651944f69fa - std::backtrace_rs::backtrace::trace_unsynchronized::h4d82d1716c5b0264
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5651944f69fa - std::sys::backtrace::_print_fmt::h65b38b72358829cc
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/sys/backtrace.rs:66:9
   3:     0x5651944f69fa - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h8b2043b14ab05304
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/sys/backtrace.rs:39:26
   4:     0x56519451f8f3 - core::fmt::rt::Argument::fmt::h4665a6919989af23
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/core/src/fmt/rt.rs:177:76
   5:     0x56519451f8f3 - core::fmt::write::hf9887d457cdbc966
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/core/src/fmt/mod.rs:1186:21
   6:     0x5651944f2573 - std::io::Write::write_fmt::ha659b10ba83556c4
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/io/mod.rs:1839:15
   7:     0x5651944f6842 - std::sys::backtrace::BacktraceLock::print::hf85affc2cf4419f7
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/sys/backtrace.rs:42:9
   8:     0x5651944f792c - std::panicking::default_hook::{{closure}}::hde5089a7c4039350
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:268:22
   9:     0x5651944f7772 - std::panicking::default_hook::hf6b38aee6b14f9c5
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:295:9
  10:     0x5651944f7f67 - std::panicking::rust_panic_with_hook::hafbd7f0e47ba5b9a
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:801:13
  11:     0x5651944f7dfa - std::panicking::begin_panic_handler::{{closure}}::heb41764772c3697f
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:674:13
  12:     0x5651944f6ed9 - std::sys::backtrace::__rust_end_short_backtrace::hcc198f67593013e0
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/sys/backtrace.rs:170:18
  13:     0x5651944f7a8c - rust_begin_unwind
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:665:5
  14:     0x56519451d230 - core::panicking::panic_fmt::hd2428fc03641ffed
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/core/src/panicking.rs:74:14
  15:     0x56519451d716 - core::result::unwrap_failed::hd8cd9da81f943b48
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/core/src/result.rs:1700:5
  16:     0x56519397b926 - core::result::Result<T,E>::unwrap::hbd196110cea1261f
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/core/src/result.rs:1104:23
  17:     0x56519397b926 - <gadget_sdk::config::EigenlayerContractAddresses as core::default::Default>::default::hfd2dd421ead3ebe5
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:132:40
  18:     0x56519397d315 - gadget_sdk::config::load_inner::h2b88328e767ee87f
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:405:36
  19:     0x56519397be9e - gadget_sdk::config::load_with_lock::h319561da837a7541
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:354:5
  20:     0x56519397be7e - gadget_sdk::config::load::hbec7f9e8b55915b0
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gadget-sdk-0.2.3/src/config.rs:339:5
  21:     0x565193748ee0 - frost_gadget::main::{{closure}}::ha43b1ab86b90b181
                               at /home/shady/github/webb-tools/frost-blueprint/src/main.rs:9:1
  22:     0x5651936ec4fb - <core::pin::Pin<P> as core::future::future::Future>::poll::hc41d171e0d6bf06c
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/core/src/future/future.rs:123:9
  23:     0x5651936fe04e - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h00d3ec8a8b1db793
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:63
  24:     0x5651936fd136 - tokio::runtime::coop::with_budget::h6ea385ce4045e87c
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
  25:     0x5651936fd136 - tokio::runtime::coop::budget::hcf75c50ac0b2824c
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
  26:     0x5651936fd136 - tokio::runtime::park::CachedParkThread::block_on::h086b9d682d2a414f
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/park.rs:281:31
  27:     0x56519370521f - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::h20a517ab0337bdba
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/blocking.rs:66:9
  28:     0x565193795bf0 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::hbad092e85de6825a
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  29:     0x5651937aca53 - tokio::runtime::context::runtime::enter_runtime::h43e0ea8eb660a40f
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
  30:     0x565193795b41 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h7faeb0e70e2e41fb
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  31:     0x565193751ea8 - tokio::runtime::runtime::Runtime::block_on_inner::ha120924776acaccd
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:363:45
  32:     0x565193752321 - tokio::runtime::runtime::Runtime::block_on::h1e367275a0078e05
                               at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:333:13
  33:     0x56519379ac41 - frost_gadget::main::h8297a5cdee182d63
                               at /home/shady/github/webb-tools/frost-blueprint/src/main.rs:9:1
  34:     0x56519370769b - core::ops::function::FnOnce::call_once::hbb64d51a9dff73e1
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  35:     0x5651936ef17e - std::sys::backtrace::__rust_begin_short_backtrace::h80da47ed9b795d04
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/std/src/sys/backtrace.rs:154:18
  36:     0x56519373b351 - std::rt::lang_start::{{closure}}::h3ff80ea34173debc
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/std/src/rt.rs:195:18
  37:     0x5651944eaf3e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6b45968bb03cc02b
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/core/src/ops/function.rs:284:13
  38:     0x5651944eaf3e - std::panicking::try::do_call::hd54f0ee6864afbc2
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:557:40
  39:     0x5651944eaf3e - std::panicking::try::h8fe1e0ae419f374f
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:520:19
  40:     0x5651944eaf3e - std::panic::catch_unwind::h3ab84fbd4591ab9b
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panic.rs:358:14
  41:     0x5651944eaf3e - std::rt::lang_start_internal::{{closure}}::h5ed0d8319bf3d939
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/rt.rs:174:48
  42:     0x5651944eaf3e - std::panicking::try::do_call::h75e456b0b947b949
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:557:40
  43:     0x5651944eaf3e - std::panicking::try::hbe8616eebdd8878b
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panicking.rs:520:19
  44:     0x5651944eaf3e - std::panic::catch_unwind::h385e8be56a3d1a7b
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/panic.rs:358:14
  45:     0x5651944eaf3e - std::rt::lang_start_internal::h6f92389acb32f739
                               at /rustc/6b9676b45431a1e531b9c5f7bd289fc36a312749/library/std/src/rt.rs:174:20
  46:     0x56519373b32a - std::rt::lang_start::h193bd9e7bbadd0ab
                               at /nix/store/1ixjn5mk15pzqfcpj4rfvv7p6xnf1y2d-rust-minimal-1.83.0-nightly-2024-10-13/lib/rustlib/src/rust/library/std/src/rt.rs:194:17
  47:     0x56519379ad0e - main
  48:     0x7f49a908b27e - __libc_start_call_main
  49:     0x7f49a908b339 - __libc_start_main_alias_2
  50:     0x5651936a1aa5 - _start
  51:                0x0 - <unknown>
```

Following the backtrace, looks like the issue is when loading the following configuration:
https://github.com/tangle-network/gadget/blob/27e774cd27f1f66d65279c1b5b854cbad178ddd3/sdk/src/config.rs#L116-L117
Which is poorly written here: https://github.com/tangle-network/gadget/blob/27e774cd27f1f66d65279c1b5b854cbad178ddd3/sdk/src/config.rs#L121-L150 no errors are handled and instead it panics with even no clear error message.

fyi; The error originally raised from here: https://github.com/tangle-network/gadget/blob/27e774cd27f1f66d65279c1b5b854cbad178ddd3/sdk/src/config.rs#L405

**Comment by shekohex** [comment]
Git blame shows the error is from this PR: #365 by @drewstone

**Comment by shekohex** [comment]
@Serial-ATA is it possible to add a CI for using the template to build and try to run the blueprint template here too? this would ensure when someone introduces a breaking change or something like that; will be caught before merging and published.

**Comment by shekohex** [comment]
I will take this task so I unblock myself while working on the FROST blueprint #370
